config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'questions#ask'
  get 'ask', to: 'questions#ask'
  get 'answer', to: 'questions#answer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end
  def answer
    question = params[:question]
    if question != nil
      if question.last == '?'
        @answer = "Silly question, get dressed and go to work!"
      elsif question == 'I am going to work'
        @answer = 'Great!'
      else
        @answer = 'I dont care, get dressed and go to work!'
      end
      return @answer
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<div class="container">
  <h1>Stupid Coaching: Answer</h1>
  <form action="/answer" method="get">
    <input type="text" name="question">
    <input type="submit" value="Ask!">
  </form>
  <div class="coach_answer">
    <p><%= "#{@answer}" %></p>
    <p>- Your coach</p>
  </div>
  <%= link_to "Ask a question to your coach", ask_path %>
</div>

app/views/questions/ask.html.erb
<div class="container">
  <h1>Stupid Coaching: Ask</h1>

  <p>Ask your coach anything!</p>

  <form action="/ask" method="get">
    <input type="text" name="question">
    <input type="submit" value="Ask!">
  </form>
  <p></p>
  <%= link_to "Claim an answer", answer_path %>
</div>